# Do not use this configuration in production.
# It is for demonstration purposes only.
multitenancy_enabled: false

blocks_storage:
  backend: s3
  bucket_store:
    sync_dir: /data/tsdb-sync
    ignore_blocks_within: 4h
  s3:
    bucket_name: mimir-storage-bucket
    region: ap-south-1
    endpoint: s3.ap-south-1.amazonaws.com
    insecure: false
  tsdb:
    dir: /tmp/mimir/tsdb
    retention_period: 5h

memberlist:
  bind_port: 7946

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  ring:
    kvstore:
      store: memberlist
    replication_factor: 1

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

server:
  http_listen_port: 9009
  grpc_listen_port: 9010
  log_level: error
  http_server_read_timeout: 600s
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
store_gateway:
  sharding_ring:
    replication_factor: 1

limits:
  out_of_order_time_window: 30m
  max_fetched_chunks_per_query: 10000000

querier:
  query_store_after: 4h
